allow localization_config.py to parse the config_example_full.json even though it does not match schema
When pulling latest adapter started getting this error. Realized it is because my config matches the old way / the example and not the schema & current parsing.

ERROR:formant_ros2_adapter:Traceback (most recent call last):
File "/app/formant_ros2_adapter/scripts/ros2_adapter.py", line 54, in setup_with_config
self.config = ConfigSchema(config["ros2_adapter_configuration"])
File "/app/formant_ros2_adapter/scripts/configuration/config_schema.py", line 23, in __init__
self.localization: Optional[LocalizationConfig] = get_value(
File "/app/formant_ros2_adapter/scripts/configuration/get_value.py", line 15, in get_value
return cls(data)
File "/app/formant_ros2_adapter/scripts/configuration/localization_config.py", line 20, in __init__
] = get_value(
File "/app/formant_ros2_adapter/scripts/configuration/get_value.py", line 13, in get_value
return [cls(item) for item in data]
File "/app/formant_ros2_adapter/scripts/configuration/get_value.py", line 13, in <listcomp>
return [cls(item) for item in data]
File "/app/formant_ros2_adapter/scripts/configuration/localization_config.py", line 43, in __init__
self.topic: str = get_value(config, "ros2_topic", required=True)
File "/app/formant_ros2_adapter/scripts/configuration/get_value.py", line 3, in get_value
data = config.get(key, None)
AttributeError: 'str' object has no attribute 'get'